os: linux
language: node_js
dist: xenial
install:
  - npm ci
cache:
  directories:
    - '~/.npm'
    - '~/.cache'
  npm: true
addons:
  sonarcloud: true
services: docker
stages:
  - name: Static code validations
  - name: Unit test & sonar-scanner
jobs:
  include:
    - stage: Static code validations
      script: commitlint-travis
      name: Commitlint verification
      env: Commitlint verification

    - script: npm run eslint:verify
      name: ESLint verification
      env: ESLint verification

    - script: npm run prettier:verify
      name: Prettier verification
      env: Prettier verification

    - script: npm run detect-secrets $( git ls-files )
      name: Detect secrets in files
      env: Detect secrets in files

    - script: npm run test:snyk
      name: Snyk test & monitor
      env: Snyk test & monitor
      after_success: npm run test:snyk:monitor

    - stage: Unit test & sonar-scanner
      script:
        - npm run test:unit
        - sonar-scanner -D sonar.organization="${SONAR_ORGANIZATION}" -D sonar.login="${SONAR_TOKEN}"
          -D sonar.projectKey="${SONAR_PROJECT_KEY}" -D sonar.projectName="${SONAR_PROJECT_NAME}"
          -D sonar.branch.name="${TRAVIS_BRANCH}"
      name: Unit test & sonar-scanner
      env: Unit test & sonar-scanner
